# Generated by Django 3.1.4 on 2024-08-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organizations',
        ),
    ]
