# Generated by Django 3.1.4 on 2024-08-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='organizations',
            new_name='organisation',
        ),
    ]
